BEGIN;

CREATE TEMP TABLE gobfuscator_anon_data
(
    idx   integer NOT NULL,
    kind  TEXT    NOT NULL,
    value TEXT    NOT NULL,
    PRIMARY KEY (idx, kind)
);

CREATE TEMP TABLE temp_gobfuscator_data_census AS
SELECT 0::bigint as total, ''::text as kind WHERE false;

-- Populate census table
INSERT INTO temp_gobfuscator_data_census
SELECT count(*) as total, kind
FROM gobfuscator_anon_data
GROUP BY kind;

-- Your update query using temp tables

insert into gobfuscator_anon_data (idx, kind, value) values (0, 'last-name', 'Anderson');
insert into gobfuscator_anon_data (idx, kind, value) values (1, 'last-name', 'Thompson');
insert into gobfuscator_anon_data (idx, kind, value) values (2, 'last-name', 'Martinez');
insert into gobfuscator_anon_data (idx, kind, value) values (3, 'last-name', 'Robinson');
insert into gobfuscator_anon_data (idx, kind, value) values (4, 'last-name', 'Clark');
insert into gobfuscator_anon_data (idx, kind, value) values (5, 'last-name', 'Rodriguez');
insert into gobfuscator_anon_data (idx, kind, value) values (6, 'last-name', 'Lewis');
insert into gobfuscator_anon_data (idx, kind, value) values (7, 'last-name', 'Walker');
insert into gobfuscator_anon_data (idx, kind, value) values (8, 'last-name', 'Hall');
insert into gobfuscator_anon_data (idx, kind, value) values (9, 'last-name', 'Allen');
insert into gobfuscator_anon_data (idx, kind, value) values (10, 'last-name', 'Young');
insert into gobfuscator_anon_data (idx, kind, value) values (11, 'last-name', 'Wright');
insert into gobfuscator_anon_data (idx, kind, value) values (12, 'last-name', 'King');
insert into gobfuscator_anon_data (idx, kind, value) values (13, 'last-name', 'Scott');
insert into gobfuscator_anon_data (idx, kind, value) values (14, 'last-name', 'Green');
insert into gobfuscator_anon_data (idx, kind, value) values (15, 'last-name', 'Baker');
insert into gobfuscator_anon_data (idx, kind, value) values (16, 'last-name', 'Adams');
insert into gobfuscator_anon_data (idx, kind, value) values (17, 'last-name', 'Nelson');
insert into gobfuscator_anon_data (idx, kind, value) values (18, 'last-name', 'Hill');
insert into gobfuscator_anon_data (idx, kind, value) values (19, 'last-name', 'Campbell');
insert into gobfuscator_anon_data (idx, kind, value) values (20, 'last-name', 'Mitchell');
insert into gobfuscator_anon_data (idx, kind, value) values (21, 'last-name', 'Roberts');
insert into gobfuscator_anon_data (idx, kind, value) values (22, 'last-name', 'Carter');
insert into gobfuscator_anon_data (idx, kind, value) values (23, 'last-name', 'Phillips');
insert into gobfuscator_anon_data (idx, kind, value) values (24, 'last-name', 'Evans');
insert into gobfuscator_anon_data (idx, kind, value) values (25, 'last-name', 'Turner');
insert into gobfuscator_anon_data (idx, kind, value) values (26, 'last-name', 'Parker');
insert into gobfuscator_anon_data (idx, kind, value) values (27, 'last-name', 'Collins');
insert into gobfuscator_anon_data (idx, kind, value) values (28, 'last-name', 'Edwards');
insert into gobfuscator_anon_data (idx, kind, value) values (29, 'last-name', 'Stewart');
insert into gobfuscator_anon_data (idx, kind, value) values (30, 'last-name', 'Morris');
insert into gobfuscator_anon_data (idx, kind, value) values (31, 'last-name', 'Murphy');
insert into gobfuscator_anon_data (idx, kind, value) values (32, 'last-name', 'Cook');
insert into gobfuscator_anon_data (idx, kind, value) values (33, 'last-name', 'Rogers');
insert into gobfuscator_anon_data (idx, kind, value) values (34, 'last-name', 'Morgan');
insert into gobfuscator_anon_data (idx, kind, value) values (35, 'last-name', 'Peterson');
insert into gobfuscator_anon_data (idx, kind, value) values (36, 'last-name', 'Cooper');
insert into gobfuscator_anon_data (idx, kind, value) values (37, 'last-name', 'Reed');
insert into gobfuscator_anon_data (idx, kind, value) values (38, 'last-name', 'Bailey');
insert into gobfuscator_anon_data (idx, kind, value) values (39, 'last-name', 'Bell');
insert into gobfuscator_anon_data (idx, kind, value) values (40, 'last-name', 'Kelly');
insert into gobfuscator_anon_data (idx, kind, value) values (41, 'last-name', 'Howard');
insert into gobfuscator_anon_data (idx, kind, value) values (42, 'last-name', 'Ward');
insert into gobfuscator_anon_data (idx, kind, value) values (43, 'last-name', 'Cox');
insert into gobfuscator_anon_data (idx, kind, value) values (44, 'last-name', 'Richardson');
insert into gobfuscator_anon_data (idx, kind, value) values (45, 'last-name', 'Wood');
insert into gobfuscator_anon_data (idx, kind, value) values (46, 'last-name', 'Watson');
insert into gobfuscator_anon_data (idx, kind, value) values (47, 'last-name', 'Brooks');
insert into gobfuscator_anon_data (idx, kind, value) values (48, 'last-name', 'Bennett');
insert into gobfuscator_anon_data (idx, kind, value) values (49, 'last-name', 'Gray');
insert into gobfuscator_anon_data (idx, kind, value) values (50, 'last-name', 'James');
insert into gobfuscator_anon_data (idx, kind, value) values (51, 'last-name', 'Hughes');
insert into gobfuscator_anon_data (idx, kind, value) values (52, 'last-name', 'Price');
insert into gobfuscator_anon_data (idx, kind, value) values (53, 'last-name', 'Myers');
insert into gobfuscator_anon_data (idx, kind, value) values (54, 'last-name', 'Long');
insert into gobfuscator_anon_data (idx, kind, value) values (55, 'last-name', 'Foster');
insert into gobfuscator_anon_data (idx, kind, value) values (56, 'last-name', 'Sanders');
insert into gobfuscator_anon_data (idx, kind, value) values (57, 'last-name', 'Ross');
insert into gobfuscator_anon_data (idx, kind, value) values (58, 'last-name', 'Powell');
insert into gobfuscator_anon_data (idx, kind, value) values (59, 'last-name', 'Sullivan');
insert into gobfuscator_anon_data (idx, kind, value) values (60, 'last-name', 'Russell');
insert into gobfuscator_anon_data (idx, kind, value) values (61, 'last-name', 'Jenkins');
insert into gobfuscator_anon_data (idx, kind, value) values (62, 'last-name', 'Perry');
insert into gobfuscator_anon_data (idx, kind, value) values (63, 'last-name', 'Butler');
insert into gobfuscator_anon_data (idx, kind, value) values (64, 'last-name', 'Barnes');
insert into gobfuscator_anon_data (idx, kind, value) values (65, 'last-name', 'Fisher');
insert into gobfuscator_anon_data (idx, kind, value) values (66, 'last-name', 'Henderson');
insert into gobfuscator_anon_data (idx, kind, value) values (67, 'last-name', 'Coleman');
insert into gobfuscator_anon_data (idx, kind, value) values (68, 'last-name', 'Simmons');
insert into gobfuscator_anon_data (idx, kind, value) values (69, 'last-name', 'Patterson');
insert into gobfuscator_anon_data (idx, kind, value) values (70, 'last-name', 'Jordan');
insert into gobfuscator_anon_data (idx, kind, value) values (71, 'last-name', 'Reynolds');
insert into gobfuscator_anon_data (idx, kind, value) values (72, 'last-name', 'Hamilton');
insert into gobfuscator_anon_data (idx, kind, value) values (73, 'last-name', 'Graham');
insert into gobfuscator_anon_data (idx, kind, value) values (74, 'last-name', 'Kim');
insert into gobfuscator_anon_data (idx, kind, value) values (75, 'last-name', 'Gonzales');
insert into gobfuscator_anon_data (idx, kind, value) values (76, 'last-name', 'Alexander');
insert into gobfuscator_anon_data (idx, kind, value) values (77, 'last-name', 'Ramos');
insert into gobfuscator_anon_data (idx, kind, value) values (78, 'last-name', 'Wallace');
insert into gobfuscator_anon_data (idx, kind, value) values (79, 'last-name', 'Griffin');
insert into gobfuscator_anon_data (idx, kind, value) values (80, 'last-name', 'West');
insert into gobfuscator_anon_data (idx, kind, value) values (81, 'last-name', 'Cole');
insert into gobfuscator_anon_data (idx, kind, value) values (82, 'last-name', 'Hayes');
insert into gobfuscator_anon_data (idx, kind, value) values (83, 'last-name', 'Chavez');
insert into gobfuscator_anon_data (idx, kind, value) values (84, 'last-name', 'Gibson');
insert into gobfuscator_anon_data (idx, kind, value) values (85, 'last-name', 'Bryant');
insert into gobfuscator_anon_data (idx, kind, value) values (86, 'last-name', 'Ellis');
insert into gobfuscator_anon_data (idx, kind, value) values (87, 'last-name', 'Stevens');
insert into gobfuscator_anon_data (idx, kind, value) values (88, 'last-name', 'Murray');
insert into gobfuscator_anon_data (idx, kind, value) values (89, 'last-name', 'Ford');
insert into gobfuscator_anon_data (idx, kind, value) values (90, 'last-name', 'Marshall');
insert into gobfuscator_anon_data (idx, kind, value) values (91, 'last-name', 'Owens');
insert into gobfuscator_anon_data (idx, kind, value) values (92, 'last-name', 'Harrison');
insert into gobfuscator_anon_data (idx, kind, value) values (93, 'last-name', 'Fernandez');
insert into gobfuscator_anon_data (idx, kind, value) values (94, 'last-name', 'Mcdonald');
insert into gobfuscator_anon_data (idx, kind, value) values (95, 'last-name', 'Woods');
insert into gobfuscator_anon_data (idx, kind, value) values (96, 'last-name', 'Washington');
insert into gobfuscator_anon_data (idx, kind, value) values (97, 'last-name', 'Kennedy');
insert into gobfuscator_anon_data (idx, kind, value) values (98, 'last-name', 'Wells');
insert into gobfuscator_anon_data (idx, kind, value) values (99, 'last-name', 'Chen');
insert into gobfuscator_anon_data (idx, kind, value) values (100, 'last-name', '');
insert into gobfuscator_anon_data (idx, kind, value) values (0, 'url', 'https://example.com');
insert into gobfuscator_anon_data (idx, kind, value) values (0, 'first-name', 'Sophia');
insert into gobfuscator_anon_data (idx, kind, value) values (1, 'first-name', 'Jackson');
insert into gobfuscator_anon_data (idx, kind, value) values (2, 'first-name', 'Ethan');
insert into gobfuscator_anon_data (idx, kind, value) values (3, 'first-name', 'Olivia');
insert into gobfuscator_anon_data (idx, kind, value) values (4, 'first-name', 'Mia');
insert into gobfuscator_anon_data (idx, kind, value) values (5, 'first-name', 'Amelia');
insert into gobfuscator_anon_data (idx, kind, value) values (6, 'first-name', 'Harper');
insert into gobfuscator_anon_data (idx, kind, value) values (7, 'first-name', 'Ava');
insert into gobfuscator_anon_data (idx, kind, value) values (8, 'first-name', 'Isabella');
insert into gobfuscator_anon_data (idx, kind, value) values (9, 'first-name', 'Abigail');
insert into gobfuscator_anon_data (idx, kind, value) values (10, 'first-name', 'Evelyn');
insert into gobfuscator_anon_data (idx, kind, value) values (11, 'first-name', 'Emily');
insert into gobfuscator_anon_data (idx, kind, value) values (12, 'first-name', 'Elizabeth');
insert into gobfuscator_anon_data (idx, kind, value) values (13, 'first-name', 'Mila');
insert into gobfuscator_anon_data (idx, kind, value) values (14, 'first-name', 'Ella');
insert into gobfuscator_anon_data (idx, kind, value) values (15, 'first-name', 'Avery');
insert into gobfuscator_anon_data (idx, kind, value) values (16, 'first-name', 'Sofia');
insert into gobfuscator_anon_data (idx, kind, value) values (17, 'first-name', 'Camila');
insert into gobfuscator_anon_data (idx, kind, value) values (18, 'first-name', 'Aria');
insert into gobfuscator_anon_data (idx, kind, value) values (19, 'first-name', 'Scarlett');
insert into gobfuscator_anon_data (idx, kind, value) values (20, 'first-name', 'Penelope');
insert into gobfuscator_anon_data (idx, kind, value) values (21, 'first-name', 'Layla');
insert into gobfuscator_anon_data (idx, kind, value) values (22, 'first-name', 'Riley');
insert into gobfuscator_anon_data (idx, kind, value) values (23, 'first-name', 'Zoey');
insert into gobfuscator_anon_data (idx, kind, value) values (24, 'first-name', 'Nora');
insert into gobfuscator_anon_data (idx, kind, value) values (25, 'first-name', 'Benjamin');
insert into gobfuscator_anon_data (idx, kind, value) values (26, 'first-name', 'Mason');
insert into gobfuscator_anon_data (idx, kind, value) values (27, 'first-name', 'William');
insert into gobfuscator_anon_data (idx, kind, value) values (28, 'first-name', 'Elijah');
insert into gobfuscator_anon_data (idx, kind, value) values (29, 'first-name', 'Oliver');
insert into gobfuscator_anon_data (idx, kind, value) values (30, 'first-name', 'Jacob');
insert into gobfuscator_anon_data (idx, kind, value) values (31, 'first-name', 'Lucas');
insert into gobfuscator_anon_data (idx, kind, value) values (32, 'first-name', 'Michael');
insert into gobfuscator_anon_data (idx, kind, value) values (33, 'first-name', 'Alexander');
insert into gobfuscator_anon_data (idx, kind, value) values (34, 'first-name', 'Sebastian');
insert into gobfuscator_anon_data (idx, kind, value) values (35, 'first-name', 'Matthew');
insert into gobfuscator_anon_data (idx, kind, value) values (36, 'first-name', 'Samuel');
insert into gobfuscator_anon_data (idx, kind, value) values (37, 'first-name', 'Daniel');
insert into gobfuscator_anon_data (idx, kind, value) values (38, 'first-name', 'David');
insert into gobfuscator_anon_data (idx, kind, value) values (39, 'first-name', 'Joseph');
insert into gobfuscator_anon_data (idx, kind, value) values (40, 'first-name', 'Carter');
insert into gobfuscator_anon_data (idx, kind, value) values (41, 'first-name', 'Owen');
insert into gobfuscator_anon_data (idx, kind, value) values (42, 'first-name', 'Wyatt');
insert into gobfuscator_anon_data (idx, kind, value) values (43, 'first-name', 'John');
insert into gobfuscator_anon_data (idx, kind, value) values (44, 'first-name', 'Jack');
insert into gobfuscator_anon_data (idx, kind, value) values (45, 'first-name', 'Luke');
insert into gobfuscator_anon_data (idx, kind, value) values (46, 'first-name', 'Jayden');
insert into gobfuscator_anon_data (idx, kind, value) values (47, 'first-name', 'Dylan');
insert into gobfuscator_anon_data (idx, kind, value) values (48, 'first-name', 'Lily');
insert into gobfuscator_anon_data (idx, kind, value) values (49, 'first-name', 'Hannah');
insert into gobfuscator_anon_data (idx, kind, value) values (50, 'first-name', 'Addison');
insert into gobfuscator_anon_data (idx, kind, value) values (51, 'first-name', 'Eleanor');
insert into gobfuscator_anon_data (idx, kind, value) values (52, 'first-name', 'Natalie');
insert into gobfuscator_anon_data (idx, kind, value) values (53, 'first-name', 'Luna');
insert into gobfuscator_anon_data (idx, kind, value) values (54, 'first-name', 'Savannah');
insert into gobfuscator_anon_data (idx, kind, value) values (55, 'first-name', 'Brooklyn');
insert into gobfuscator_anon_data (idx, kind, value) values (56, 'first-name', 'Leah');
insert into gobfuscator_anon_data (idx, kind, value) values (57, 'first-name', 'Zoe');
insert into gobfuscator_anon_data (idx, kind, value) values (58, 'first-name', 'Stella');
insert into gobfuscator_anon_data (idx, kind, value) values (59, 'first-name', 'Hazel');
insert into gobfuscator_anon_data (idx, kind, value) values (60, 'first-name', 'Ellie');
insert into gobfuscator_anon_data (idx, kind, value) values (61, 'first-name', 'Paisley');
insert into gobfuscator_anon_data (idx, kind, value) values (62, 'first-name', 'Audrey');
insert into gobfuscator_anon_data (idx, kind, value) values (63, 'first-name', 'Skylar');
insert into gobfuscator_anon_data (idx, kind, value) values (64, 'first-name', 'Violet');
insert into gobfuscator_anon_data (idx, kind, value) values (65, 'first-name', 'Claire');
insert into gobfuscator_anon_data (idx, kind, value) values (66, 'first-name', 'Bella');
insert into gobfuscator_anon_data (idx, kind, value) values (67, 'first-name', 'Aurora');
insert into gobfuscator_anon_data (idx, kind, value) values (68, 'first-name', 'Lucy');
insert into gobfuscator_anon_data (idx, kind, value) values (69, 'first-name', 'Anna');
insert into gobfuscator_anon_data (idx, kind, value) values (70, 'first-name', 'Samantha');
insert into gobfuscator_anon_data (idx, kind, value) values (71, 'first-name', 'Caroline');
insert into gobfuscator_anon_data (idx, kind, value) values (72, 'first-name', 'Nathan');
insert into gobfuscator_anon_data (idx, kind, value) values (73, 'first-name', 'Andrew');
insert into gobfuscator_anon_data (idx, kind, value) values (74, 'first-name', 'Joshua');
insert into gobfuscator_anon_data (idx, kind, value) values (75, 'first-name', 'Christopher');
insert into gobfuscator_anon_data (idx, kind, value) values (76, 'first-name', 'Theodore');
insert into gobfuscator_anon_data (idx, kind, value) values (77, 'first-name', 'Ryan');
insert into gobfuscator_anon_data (idx, kind, value) values (78, 'first-name', 'Adrian');
insert into gobfuscator_anon_data (idx, kind, value) values (79, 'first-name', 'Isaac');
insert into gobfuscator_anon_data (idx, kind, value) values (80, 'first-name', 'Hudson');
insert into gobfuscator_anon_data (idx, kind, value) values (81, 'first-name', 'Evan');
insert into gobfuscator_anon_data (idx, kind, value) values (82, 'first-name', 'Jeremiah');
insert into gobfuscator_anon_data (idx, kind, value) values (83, 'first-name', 'Easton');
insert into gobfuscator_anon_data (idx, kind, value) values (84, 'first-name', 'Colton');
insert into gobfuscator_anon_data (idx, kind, value) values (85, 'first-name', 'Cameron');
insert into gobfuscator_anon_data (idx, kind, value) values (86, 'first-name', 'Carson');
insert into gobfuscator_anon_data (idx, kind, value) values (87, 'first-name', 'Robert');
insert into gobfuscator_anon_data (idx, kind, value) values (88, 'first-name', 'Angel');
insert into gobfuscator_anon_data (idx, kind, value) values (89, 'first-name', 'Maverick');
insert into gobfuscator_anon_data (idx, kind, value) values (90, 'first-name', 'Nicholas');
insert into gobfuscator_anon_data (idx, kind, value) values (91, 'first-name', 'Dominic');
insert into gobfuscator_anon_data (idx, kind, value) values (92, 'first-name', 'Jaxson');
insert into gobfuscator_anon_data (idx, kind, value) values (93, 'first-name', 'Greyson');
insert into gobfuscator_anon_data (idx, kind, value) values (94, 'first-name', 'Adam');
insert into gobfuscator_anon_data (idx, kind, value) values (95, 'first-name', 'Ian');
insert into gobfuscator_anon_data (idx, kind, value) values (96, 'first-name', 'Austin');
insert into gobfuscator_anon_data (idx, kind, value) values (97, 'first-name', 'Santiago');
insert into gobfuscator_anon_data (idx, kind, value) values (98, 'first-name', 'Jordan');
insert into gobfuscator_anon_data (idx, kind, value) values (99, 'first-name', 'Cooper');
insert into gobfuscator_anon_data (idx, kind, value) values (100, 'first-name', 'Brayden');
insert into gobfuscator_anon_data (idx, kind, value) values (101, 'first-name', 'Roman');
insert into gobfuscator_anon_data (idx, kind, value) values (102, 'first-name', 'Ezra');
insert into gobfuscator_anon_data (idx, kind, value) values (103, 'first-name', 'Wesley');
insert into gobfuscator_anon_data (idx, kind, value) values (104, 'first-name', 'Kayden');
insert into gobfuscator_anon_data (idx, kind, value) values (105, 'first-name', 'Jason');
insert into gobfuscator_anon_data (idx, kind, value) values (106, 'first-name', 'Miles');
insert into gobfuscator_anon_data (idx, kind, value) values (107, 'first-name', 'Chase');
insert into gobfuscator_anon_data (idx, kind, value) values (108, 'first-name', 'Axel');
insert into gobfuscator_anon_data (idx, kind, value) values (109, 'first-name', 'Eric');
insert into gobfuscator_anon_data (idx, kind, value) values (110, 'first-name', 'Blake');
insert into gobfuscator_anon_data (idx, kind, value) values (0, 'state', 'WA');
insert into gobfuscator_anon_data (idx, kind, value) values (1, 'state', 'OR');
insert into gobfuscator_anon_data (idx, kind, value) values (2, 'state', 'CA');
insert into gobfuscator_anon_data (idx, kind, value) values (3, 'state', 'NV');
insert into gobfuscator_anon_data (idx, kind, value) values (4, 'state', 'ID');
insert into gobfuscator_anon_data (idx, kind, value) values (5, 'state', 'MT');
insert into gobfuscator_anon_data (idx, kind, value) values (6, 'state', 'WY');
insert into gobfuscator_anon_data (idx, kind, value) values (7, 'state', 'UT');
insert into gobfuscator_anon_data (idx, kind, value) values (8, 'state', 'CO');
insert into gobfuscator_anon_data (idx, kind, value) values (9, 'state', 'AZ');
insert into gobfuscator_anon_data (idx, kind, value) values (10, 'state', 'NM');
insert into gobfuscator_anon_data (idx, kind, value) values (11, 'state', 'TX');
insert into gobfuscator_anon_data (idx, kind, value) values (12, 'state', 'OK');
insert into gobfuscator_anon_data (idx, kind, value) values (13, 'state', 'KS');
insert into gobfuscator_anon_data (idx, kind, value) values (14, 'state', 'NE');
insert into gobfuscator_anon_data (idx, kind, value) values (15, 'state', 'SD');
insert into gobfuscator_anon_data (idx, kind, value) values (16, 'state', 'ND');
insert into gobfuscator_anon_data (idx, kind, value) values (17, 'state', 'MN');
insert into gobfuscator_anon_data (idx, kind, value) values (18, 'state', 'IA');
insert into gobfuscator_anon_data (idx, kind, value) values (19, 'state', 'MO');
insert into gobfuscator_anon_data (idx, kind, value) values (20, 'state', 'AR');
insert into gobfuscator_anon_data (idx, kind, value) values (21, 'state', 'LA');
insert into gobfuscator_anon_data (idx, kind, value) values (22, 'state', 'MS');
insert into gobfuscator_anon_data (idx, kind, value) values (23, 'state', 'AL');
insert into gobfuscator_anon_data (idx, kind, value) values (24, 'state', 'GA');
insert into gobfuscator_anon_data (idx, kind, value) values (25, 'state', 'FL');
insert into gobfuscator_anon_data (idx, kind, value) values (26, 'state', 'SC');
insert into gobfuscator_anon_data (idx, kind, value) values (27, 'state', 'NC');
insert into gobfuscator_anon_data (idx, kind, value) values (28, 'state', 'TN');
insert into gobfuscator_anon_data (idx, kind, value) values (29, 'state', 'KY');
insert into gobfuscator_anon_data (idx, kind, value) values (30, 'state', 'VA');
insert into gobfuscator_anon_data (idx, kind, value) values (31, 'state', 'WV');
insert into gobfuscator_anon_data (idx, kind, value) values (32, 'state', 'OH');
insert into gobfuscator_anon_data (idx, kind, value) values (33, 'state', 'MI');
insert into gobfuscator_anon_data (idx, kind, value) values (34, 'state', 'IN');
insert into gobfuscator_anon_data (idx, kind, value) values (35, 'state', 'IL');
insert into gobfuscator_anon_data (idx, kind, value) values (36, 'state', 'OR');
insert into gobfuscator_anon_data (idx, kind, value) values (37, 'state', 'PA');
insert into gobfuscator_anon_data (idx, kind, value) values (38, 'state', 'RI');
insert into gobfuscator_anon_data (idx, kind, value) values (39, 'state', 'SC');
insert into gobfuscator_anon_data (idx, kind, value) values (40, 'state', 'SD');
insert into gobfuscator_anon_data (idx, kind, value) values (41, 'state', 'TN');
insert into gobfuscator_anon_data (idx, kind, value) values (42, 'state', 'TX');
insert into gobfuscator_anon_data (idx, kind, value) values (43, 'state', 'UT');
insert into gobfuscator_anon_data (idx, kind, value) values (44, 'state', 'VT');
insert into gobfuscator_anon_data (idx, kind, value) values (45, 'state', 'VA');
insert into gobfuscator_anon_data (idx, kind, value) values (46, 'state', 'WA');
insert into gobfuscator_anon_data (idx, kind, value) values (47, 'state', 'WV');
insert into gobfuscator_anon_data (idx, kind, value) values (48, 'state', 'WI');
insert into gobfuscator_anon_data (idx, kind, value) values (49, 'state', 'WY');
insert into gobfuscator_anon_data (idx, kind, value) values (50, 'state', '');
insert into gobfuscator_anon_data (idx, kind, value) values (0, 'email', 'contact@example.org');
insert into gobfuscator_anon_data (idx, kind, value) values (0, 'geo-location', '{"latitude" : 37.7749, "longitude": -122.4194}');
insert into gobfuscator_anon_data (idx, kind, value) values (1, 'geo-location', '{"latitude" : 40.7128, "longitude": -74.0060}');
insert into gobfuscator_anon_data (idx, kind, value) values (2, 'geo-location', '{"latitude" : 51.5074, "longitude": -0.1278}');
insert into gobfuscator_anon_data (idx, kind, value) values (3, 'geo-location', '{"latitude" : 48.8566, "longitude": 2.3522}');
insert into gobfuscator_anon_data (idx, kind, value) values (4, 'geo-location', '{"latitude" : 35.6762, "longitude": 139.6503}');
insert into gobfuscator_anon_data (idx, kind, value) values (5, 'geo-location', '{"latitude" : 22.3193, "longitude": 114.1694}');
insert into gobfuscator_anon_data (idx, kind, value) values (6, 'geo-location', '{"latitude" : -33.8688, "longitude": 151.2093}');
insert into gobfuscator_anon_data (idx, kind, value) values (7, 'geo-location', '{"latitude" : -34.6037, "longitude": -58.3816}');
insert into gobfuscator_anon_data (idx, kind, value) values (8, 'geo-location', '{"latitude" : 55.7558, "longitude": 37.6173}');
insert into gobfuscator_anon_data (idx, kind, value) values (0, 'word', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.');
insert into gobfuscator_anon_data (idx, kind, value) values (1, 'word', '');
insert into gobfuscator_anon_data (idx, kind, value) values (2, 'word', '');
insert into gobfuscator_anon_data (idx, kind, value) values (3, 'word', 'A catalyst for change.');
insert into gobfuscator_anon_data (idx, kind, value) values (4, 'word', '');
insert into gobfuscator_anon_data (idx, kind, value) values (5, 'word', '');
insert into gobfuscator_anon_data (idx, kind, value) values (6, 'word', '');
insert into gobfuscator_anon_data (idx, kind, value) values (7, 'word', '');
insert into gobfuscator_anon_data (idx, kind, value) values (8, 'word', '');
insert into gobfuscator_anon_data (idx, kind, value) values (9, 'word', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit – a timeless sequence.');
insert into gobfuscator_anon_data (idx, kind, value) values (10, 'word', '');
insert into gobfuscator_anon_data (idx, kind, value) values (11, 'word', '');
insert into gobfuscator_anon_data (idx, kind, value) values (12, 'word', 'Timeless phrase echoing through the ages.');
insert into gobfuscator_anon_data (idx, kind, value) values (13, 'word', '');
insert into gobfuscator_anon_data (idx, kind, value) values (14, 'word', '');
insert into gobfuscator_anon_data (idx, kind, value) values (15, 'word', '');
insert into gobfuscator_anon_data (idx, kind, value) values (16, 'word', '');
insert into gobfuscator_anon_data (idx, kind, value) values (17, 'word', '');
insert into gobfuscator_anon_data (idx, kind, value) values (18, 'word', 'Through lorem ipsum dolor sit amet wisdom emerges. (17 word)');
insert into gobfuscator_anon_data (idx, kind, value) values (19, 'word', '');
insert into gobfuscator_anon_data (idx, kind, value) values (0, 'city', 'Springfield');
insert into gobfuscator_anon_data (idx, kind, value) values (1, 'city', 'Riverside');
insert into gobfuscator_anon_data (idx, kind, value) values (2, 'city', 'Georgetown');
insert into gobfuscator_anon_data (idx, kind, value) values (3, 'city', 'Franklin');
insert into gobfuscator_anon_data (idx, kind, value) values (4, 'city', 'Bristol');
insert into gobfuscator_anon_data (idx, kind, value) values (5, 'city', 'Clinton');
insert into gobfuscator_anon_data (idx, kind, value) values (6, 'city', 'Fairview');
insert into gobfuscator_anon_data (idx, kind, value) values (7, 'city', 'Salem');
insert into gobfuscator_anon_data (idx, kind, value) values (8, 'city', 'Madison');
insert into gobfuscator_anon_data (idx, kind, value) values (9, 'city', 'Oxford');
insert into gobfuscator_anon_data (idx, kind, value) values (10, 'city', 'Arlington');
insert into gobfuscator_anon_data (idx, kind, value) values (11, 'city', 'Burlington');
insert into gobfuscator_anon_data (idx, kind, value) values (12, 'city', 'Dover');
insert into gobfuscator_anon_data (idx, kind, value) values (13, 'city', 'Greenville');
insert into gobfuscator_anon_data (idx, kind, value) values (14, 'city', 'Kingston');
insert into gobfuscator_anon_data (idx, kind, value) values (15, 'city', 'Newport');
insert into gobfuscator_anon_data (idx, kind, value) values (16, 'city', 'Oakland');
insert into gobfuscator_anon_data (idx, kind, value) values (17, 'city', 'Ashland');
insert into gobfuscator_anon_data (idx, kind, value) values (18, 'city', 'Burlington');
insert into gobfuscator_anon_data (idx, kind, value) values (19, 'city', 'Manchester');
insert into gobfuscator_anon_data (idx, kind, value) values (20, 'city', 'Plymouth');
insert into gobfuscator_anon_data (idx, kind, value) values (21, 'city', 'Westport');
insert into gobfuscator_anon_data (idx, kind, value) values (22, 'city', 'Centerville');
insert into gobfuscator_anon_data (idx, kind, value) values (23, 'city', 'Dayton');
insert into gobfuscator_anon_data (idx, kind, value) values (24, 'city', 'Lexington');
insert into gobfuscator_anon_data (idx, kind, value) values (25, 'city', 'Milford');
insert into gobfuscator_anon_data (idx, kind, value) values (26, 'city', 'Winchester');
insert into gobfuscator_anon_data (idx, kind, value) values (27, 'city', 'Auburn');
insert into gobfuscator_anon_data (idx, kind, value) values (28, 'city', 'Glenwood');
insert into gobfuscator_anon_data (idx, kind, value) values (29, 'city', 'Hudson');
insert into gobfuscator_anon_data (idx, kind, value) values (30, 'city', 'Milton');
insert into gobfuscator_anon_data (idx, kind, value) values (31, 'city', 'Ridgewood');
insert into gobfuscator_anon_data (idx, kind, value) values (32, 'city', 'Walnut Creek');
insert into gobfuscator_anon_data (idx, kind, value) values (33, 'city', 'Belmont');
insert into gobfuscator_anon_data (idx, kind, value) values (34, 'city', 'Clearwater');
insert into gobfuscator_anon_data (idx, kind, value) values (35, 'city', 'Fairfield');
insert into gobfuscator_anon_data (idx, kind, value) values (36, 'city', 'Lakewood');
insert into gobfuscator_anon_data (idx, kind, value) values (37, 'city', 'Maplewood');
insert into gobfuscator_anon_data (idx, kind, value) values (38, 'city', 'Roseville');
insert into gobfuscator_anon_data (idx, kind, value) values (39, 'city', 'Woodbury');
insert into gobfuscator_anon_data (idx, kind, value) values (40, 'city', 'Brentwood');
insert into gobfuscator_anon_data (idx, kind, value) values (41, 'city', 'Danville');
insert into gobfuscator_anon_data (idx, kind, value) values (42, 'city', 'Elmwood');
insert into gobfuscator_anon_data (idx, kind, value) values (43, 'city', 'Glendale');
insert into gobfuscator_anon_data (idx, kind, value) values (44, 'city', 'Highland Park');
insert into gobfuscator_anon_data (idx, kind, value) values (45, 'city', 'Lakeside');
insert into gobfuscator_anon_data (idx, kind, value) values (46, 'city', 'Millbrook');
insert into gobfuscator_anon_data (idx, kind, value) values (47, 'city', 'Newtown');
insert into gobfuscator_anon_data (idx, kind, value) values (48, 'city', 'Oakdale');
insert into gobfuscator_anon_data (idx, kind, value) values (49, 'city', 'Parkville');
insert into gobfuscator_anon_data (idx, kind, value) values (50, 'city', 'Redmond');
insert into gobfuscator_anon_data (idx, kind, value) values (51, 'city', 'Southfield');
insert into gobfuscator_anon_data (idx, kind, value) values (52, 'city', 'Westfield');
insert into gobfuscator_anon_data (idx, kind, value) values (53, 'city', 'Brookside');
insert into gobfuscator_anon_data (idx, kind, value) values (54, 'city', 'Cedar Grove');
insert into gobfuscator_anon_data (idx, kind, value) values (55, 'city', 'Edgewater');
insert into gobfuscator_anon_data (idx, kind, value) values (56, 'city', 'Forest Hills');
insert into gobfuscator_anon_data (idx, kind, value) values (57, 'city', 'Granite Bay');
insert into gobfuscator_anon_data (idx, kind, value) values (58, 'city', 'Hillcrest');
insert into gobfuscator_anon_data (idx, kind, value) values (59, 'city', 'Lakeview');
insert into gobfuscator_anon_data (idx, kind, value) values (60, 'city', 'Meadowbrook');
insert into gobfuscator_anon_data (idx, kind, value) values (61, 'city', 'Northridge');
insert into gobfuscator_anon_data (idx, kind, value) values (62, 'city', 'Pinehurst');
insert into gobfuscator_anon_data (idx, kind, value) values (63, 'city', 'Riverdale');
insert into gobfuscator_anon_data (idx, kind, value) values (64, 'city', 'Stonehaven');
insert into gobfuscator_anon_data (idx, kind, value) values (65, 'city', 'Valleyview');
insert into gobfuscator_anon_data (idx, kind, value) values (66, 'city', 'Woodridge');
insert into gobfuscator_anon_data (idx, kind, value) values (67, 'city', 'Bayshore');
insert into gobfuscator_anon_data (idx, kind, value) values (68, 'city', 'Crestwood');
insert into gobfuscator_anon_data (idx, kind, value) values (69, 'city', 'Eastlake');
insert into gobfuscator_anon_data (idx, kind, value) values (70, 'city', 'Fairmont');
insert into gobfuscator_anon_data (idx, kind, value) values (71, 'city', 'Greenwood');
insert into gobfuscator_anon_data (idx, kind, value) values (72, 'city', 'Harborview');
insert into gobfuscator_anon_data (idx, kind, value) values (73, 'city', 'Inglewood');
insert into gobfuscator_anon_data (idx, kind, value) values (74, 'city', 'Kenwood');
insert into gobfuscator_anon_data (idx, kind, value) values (75, 'city', 'Laurelwood');
insert into gobfuscator_anon_data (idx, kind, value) values (76, 'city', 'Morningside');
insert into gobfuscator_anon_data (idx, kind, value) values (77, 'city', 'Northwood');
insert into gobfuscator_anon_data (idx, kind, value) values (78, 'city', 'Oakwood');
insert into gobfuscator_anon_data (idx, kind, value) values (79, 'city', 'Pinecrest');
insert into gobfuscator_anon_data (idx, kind, value) values (80, 'city', 'Queensbury');
insert into gobfuscator_anon_data (idx, kind, value) values (81, 'city', 'Ridgefield');
insert into gobfuscator_anon_data (idx, kind, value) values (82, 'city', 'Sunnyvale');
insert into gobfuscator_anon_data (idx, kind, value) values (83, 'city', 'Thornwood');
insert into gobfuscator_anon_data (idx, kind, value) values (84, 'city', 'Upland');
insert into gobfuscator_anon_data (idx, kind, value) values (85, 'city', 'Valleydale');
insert into gobfuscator_anon_data (idx, kind, value) values (86, 'city', 'Westlake');
insert into gobfuscator_anon_data (idx, kind, value) values (87, 'city', 'Woodlawn');
insert into gobfuscator_anon_data (idx, kind, value) values (88, 'city', 'Bayside');
insert into gobfuscator_anon_data (idx, kind, value) values (89, 'city', 'Claremont');
insert into gobfuscator_anon_data (idx, kind, value) values (90, 'city', 'Eastwood');
insert into gobfuscator_anon_data (idx, kind, value) values (91, 'city', 'Fairhaven');
insert into gobfuscator_anon_data (idx, kind, value) values (92, 'city', 'Glenview');
insert into gobfuscator_anon_data (idx, kind, value) values (93, 'city', 'Highland');
insert into gobfuscator_anon_data (idx, kind, value) values (94, 'city', 'Lakeland');
insert into gobfuscator_anon_data (idx, kind, value) values (95, 'city', 'Millcreek');
insert into gobfuscator_anon_data (idx, kind, value) values (96, 'city', 'Newbury');
insert into gobfuscator_anon_data (idx, kind, value) values (97, 'city', 'Oakmont');
insert into gobfuscator_anon_data (idx, kind, value) values (98, 'city', 'Parkside');
insert into gobfuscator_anon_data (idx, kind, value) values (99, 'city', 'Redwood');
insert into gobfuscator_anon_data (idx, kind, value) values (100, 'city', 'Southgate');
insert into gobfuscator_anon_data (idx, kind, value) values (101, 'city', 'Westmont');
insert into gobfuscator_anon_data (idx, kind, value) values (102, 'city', '');
insert into gobfuscator_anon_data (idx, kind, value) values (0, 'address-1', 'Mountain View Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (1, 'address-1', 'Sunset Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (2, 'address-1', 'Ocean Ave');
insert into gobfuscator_anon_data (idx, kind, value) values (3, 'address-1', 'Forest St');
insert into gobfuscator_anon_data (idx, kind, value) values (4, 'address-1', 'Valley Rd');
insert into gobfuscator_anon_data (idx, kind, value) values (5, 'address-1', 'Highland Blvd');
insert into gobfuscator_anon_data (idx, kind, value) values (6, 'address-1', 'Meadow Grove Cir');
insert into gobfuscator_anon_data (idx, kind, value) values (7, 'address-1', 'Lakewood Pl');
insert into gobfuscator_anon_data (idx, kind, value) values (8, 'address-1', 'Riverwood Tr');
insert into gobfuscator_anon_data (idx, kind, value) values (9, 'address-1', 'Hillside Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (10, 'address-1', 'Brookside Way');
insert into gobfuscator_anon_data (idx, kind, value) values (11, 'address-1', 'Canyon Loop');
insert into gobfuscator_anon_data (idx, kind, value) values (12, 'address-1', 'Silver Creek Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (13, 'address-1', 'Golden Gate Ct');
insert into gobfuscator_anon_data (idx, kind, value) values (14, 'address-1', 'Bayview Blvd');
insert into gobfuscator_anon_data (idx, kind, value) values (15, 'address-1', 'Harbor Point St');
insert into gobfuscator_anon_data (idx, kind, value) values (16, 'address-1', 'Lighthouse Rd');
insert into gobfuscator_anon_data (idx, kind, value) values (17, 'address-1', 'Coastal Oak Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (18, 'address-1', 'Seabreeze Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (19, 'address-1', 'Misty Cir');
insert into gobfuscator_anon_data (idx, kind, value) values (20, 'address-1', 'Foggy Ridge Ct');
insert into gobfuscator_anon_data (idx, kind, value) values (21, 'address-1', 'Sunny Dale Blvd');
insert into gobfuscator_anon_data (idx, kind, value) values (22, 'address-1', 'Clear Water Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (23, 'address-1', 'Blue Sky Ave');
insert into gobfuscator_anon_data (idx, kind, value) values (24, 'address-1', 'Windy Hill St');
insert into gobfuscator_anon_data (idx, kind, value) values (25, 'address-1', 'Stony Brook Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (26, 'address-1', 'Rolling Hills Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (27, 'address-1', 'Pleasant Valley Blvd');
insert into gobfuscator_anon_data (idx, kind, value) values (28, 'address-1', 'Green Meadow Tr');
insert into gobfuscator_anon_data (idx, kind, value) values (29, 'address-1', 'Timber Ridge Rd');
insert into gobfuscator_anon_data (idx, kind, value) values (30, 'address-1', 'Golden Pond Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (31, 'address-1', 'Willow St');
insert into gobfuscator_anon_data (idx, kind, value) values (32, 'address-1', 'Orchard Grove Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (33, 'address-1', 'Garden View Ct');
insert into gobfuscator_anon_data (idx, kind, value) values (34, 'address-1', 'Park Place Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (35, 'address-1', 'Shady Elm Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (36, 'address-1', 'Wildflower Tr');
insert into gobfuscator_anon_data (idx, kind, value) values (37, 'address-1', 'Fern Rd');
insert into gobfuscator_anon_data (idx, kind, value) values (38, 'address-1', 'Granite Ridge Rd');
insert into gobfuscator_anon_data (idx, kind, value) values (39, 'address-1', 'Mossy Oak Way');
insert into gobfuscator_anon_data (idx, kind, value) values (40, 'address-1', 'Whispering Pine Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (41, 'address-1', 'Autumn Leaf St');
insert into gobfuscator_anon_data (idx, kind, value) values (42, 'address-1', 'Spring Valley Cir');
insert into gobfuscator_anon_data (idx, kind, value) values (43, 'address-1', 'Summer Breeze Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (44, 'address-1', 'Winter Haven Ave');
insert into gobfuscator_anon_data (idx, kind, value) values (45, 'address-1', 'Harvest Moon Cir');
insert into gobfuscator_anon_data (idx, kind, value) values (46, 'address-1', 'Morning Glory Tr');
insert into gobfuscator_anon_data (idx, kind, value) values (47, 'address-1', 'Evening Star Rd');
insert into gobfuscator_anon_data (idx, kind, value) values (48, 'address-1', 'Sunrise Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (49, 'address-1', 'Twilight St');
insert into gobfuscator_anon_data (idx, kind, value) values (50, 'address-1', 'Moonlight Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (51, 'address-1', 'Starlight Rd');
insert into gobfuscator_anon_data (idx, kind, value) values (52, 'address-1', 'Rainbow Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (53, 'address-1', 'Crystal Lake Ave');
insert into gobfuscator_anon_data (idx, kind, value) values (54, 'address-1', 'Diamond Ridge Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (55, 'address-1', 'Emerald Isle Rd');
insert into gobfuscator_anon_data (idx, kind, value) values (56, 'address-1', 'Ruby Glen Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (57, 'address-1', 'Sapphire Ct');
insert into gobfuscator_anon_data (idx, kind, value) values (58, 'address-1', 'Amber Way');
insert into gobfuscator_anon_data (idx, kind, value) values (59, 'address-1', 'Pearl St');
insert into gobfuscator_anon_data (idx, kind, value) values (60, 'address-1', 'Jade Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (61, 'address-1', 'Opal Rd');
insert into gobfuscator_anon_data (idx, kind, value) values (62, 'address-1', 'Topaz Blvd');
insert into gobfuscator_anon_data (idx, kind, value) values (63, 'address-1', 'Turquoise St');
insert into gobfuscator_anon_data (idx, kind, value) values (64, 'address-1', 'Coral Way');
insert into gobfuscator_anon_data (idx, kind, value) values (65, 'address-1', 'Ivory Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (66, 'address-1', 'Cobblestone Rd');
insert into gobfuscator_anon_data (idx, kind, value) values (67, 'address-1', 'Fieldstone Blvd');
insert into gobfuscator_anon_data (idx, kind, value) values (68, 'address-1', 'Pebble Beach Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (69, 'address-1', 'Sandy Shore Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (70, 'address-1', 'Rocky Point Blvd');
insert into gobfuscator_anon_data (idx, kind, value) values (71, 'address-1', 'Driftwood Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (72, 'address-1', 'Seaside St');
insert into gobfuscator_anon_data (idx, kind, value) values (73, 'address-1', 'Bayside Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (74, 'address-1', 'Lakeview Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (75, 'address-1', 'Riverview Ave');
insert into gobfuscator_anon_data (idx, kind, value) values (76, 'address-1', 'Creekside St');
insert into gobfuscator_anon_data (idx, kind, value) values (77, 'address-1', 'Streamside Blvd');
insert into gobfuscator_anon_data (idx, kind, value) values (78, 'address-1', 'Waterfront Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (79, 'address-1', 'Shoreline Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (80, 'address-1', 'Beachfront Blvd');
insert into gobfuscator_anon_data (idx, kind, value) values (81, 'address-1', 'Harborview St');
insert into gobfuscator_anon_data (idx, kind, value) values (82, 'address-1', 'Bayshore Rd');
insert into gobfuscator_anon_data (idx, kind, value) values (83, 'address-1', 'Oceanview Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (84, 'address-1', 'Cliffside Tr');
insert into gobfuscator_anon_data (idx, kind, value) values (85, 'address-1', 'Hilltop Rd');
insert into gobfuscator_anon_data (idx, kind, value) values (86, 'address-1', 'Summit Blvd');
insert into gobfuscator_anon_data (idx, kind, value) values (87, 'address-1', 'Vista Point Way');
insert into gobfuscator_anon_data (idx, kind, value) values (88, 'address-1', 'Panorama Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (89, 'address-1', 'Skyline Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (90, 'address-1', 'Horizon Rd');
insert into gobfuscator_anon_data (idx, kind, value) values (91, 'address-1', 'Overlook St');
insert into gobfuscator_anon_data (idx, kind, value) values (92, 'address-1', 'Lookout Blvd');
insert into gobfuscator_anon_data (idx, kind, value) values (93, 'address-1', 'Viewpoint Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (94, 'address-1', 'Prospect Ave');
insert into gobfuscator_anon_data (idx, kind, value) values (0, 'street', '1 Cherry Blossom Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (1, 'street', '2 Maple Leaf Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (2, 'street', '3 Pinecone Ave');
insert into gobfuscator_anon_data (idx, kind, value) values (3, 'street', '4 Acorn St');
insert into gobfuscator_anon_data (idx, kind, value) values (4, 'street', '5 Redwood Rd');
insert into gobfuscator_anon_data (idx, kind, value) values (5, 'street', '6 Evergreen Blvd');
insert into gobfuscator_anon_data (idx, kind, value) values (6, 'street', '7 Aspen Grove Cir');
insert into gobfuscator_anon_data (idx, kind, value) values (7, 'street', '8 Birchwood Pl');
insert into gobfuscator_anon_data (idx, kind, value) values (8, 'street', '9 Cedarwood Tr');
insert into gobfuscator_anon_data (idx, kind, value) values (9, 'street', '10 Dogwood Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (10, 'street', '11 Elderberry Way');
insert into gobfuscator_anon_data (idx, kind, value) values (11, 'street', '12 Firwood Loop');
insert into gobfuscator_anon_data (idx, kind, value) values (12, 'street', '13 Green Twig Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (13, 'street', '14 Hazel Nut Ct');
insert into gobfuscator_anon_data (idx, kind, value) values (14, 'street', '15 Ironwood Blvd');
insert into gobfuscator_anon_data (idx, kind, value) values (15, 'street', '16 Juniper Berry St');
insert into gobfuscator_anon_data (idx, kind, value) values (16, 'street', '17 Kingwood Rd');
insert into gobfuscator_anon_data (idx, kind, value) values (17, 'street', '18 Laurel Oak Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (18, 'street', '19 Magnolia Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (19, 'street', '20 Nutmeg Cir');
insert into gobfuscator_anon_data (idx, kind, value) values (20, 'street', '21 Orange Peel Ct');
insert into gobfuscator_anon_data (idx, kind, value) values (21, 'street', '22 Pecan Grove Blvd');
insert into gobfuscator_anon_data (idx, kind, value) values (22, 'street', '23 Quince Tree Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (23, 'street', '24 Red Bud Ave');
insert into gobfuscator_anon_data (idx, kind, value) values (24, 'street', '25 Sassafras St');
insert into gobfuscator_anon_data (idx, kind, value) values (25, 'street', '26 Teakwood Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (26, 'street', '27 Umbrella Pine Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (27, 'street', '28 Vanilla Bean Blvd');
insert into gobfuscator_anon_data (idx, kind, value) values (28, 'street', '29 Walnut Grove Tr');
insert into gobfuscator_anon_data (idx, kind, value) values (29, 'street', '30 Xylem Rd');
insert into gobfuscator_anon_data (idx, kind, value) values (30, 'street', '31 Yellow Pine Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (31, 'street', '32 Zinnia St');
insert into gobfuscator_anon_data (idx, kind, value) values (32, 'street', '33 Apple Grove Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (33, 'street', '34 Banana Ct');
insert into gobfuscator_anon_data (idx, kind, value) values (34, 'street', '35 Cantaloupe Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (35, 'street', '36 Date Palm Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (36, 'street', '37 Elderberry Tr');
insert into gobfuscator_anon_data (idx, kind, value) values (37, 'street', '38 Fig Rd');
insert into gobfuscator_anon_data (idx, kind, value) values (38, 'street', '39 Grapefruit Grove Rd');
insert into gobfuscator_anon_data (idx, kind, value) values (39, 'street', '40 Hickory Nut Way');
insert into gobfuscator_anon_data (idx, kind, value) values (40, 'street', '41 Indian Plum Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (41, 'street', '42 Jackfruit St');
insert into gobfuscator_anon_data (idx, kind, value) values (42, 'street', '43 Kiwi Cir');
insert into gobfuscator_anon_data (idx, kind, value) values (43, 'street', '44 Lychee Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (44, 'street', '45 Mango Ave');
insert into gobfuscator_anon_data (idx, kind, value) values (45, 'street', '46 Nectarine Cir');
insert into gobfuscator_anon_data (idx, kind, value) values (46, 'street', '47 Olive Tree Tr');
insert into gobfuscator_anon_data (idx, kind, value) values (47, 'street', '48 Papaya Rd');
insert into gobfuscator_anon_data (idx, kind, value) values (48, 'street', '49 Quandong Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (49, 'street', '50 Raspberry St');
insert into gobfuscator_anon_data (idx, kind, value) values (50, 'street', '51 Starfruit Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (51, 'street', '52 Tangerine Rd');
insert into gobfuscator_anon_data (idx, kind, value) values (52, 'street', '53 Ugli Fruit Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (53, 'street', '54 Velvet Apple Ave');
insert into gobfuscator_anon_data (idx, kind, value) values (54, 'street', '55 Watermelon Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (55, 'street', '56 Xigua Melon Rd');
insert into gobfuscator_anon_data (idx, kind, value) values (56, 'street', '57 Yellow Passionfruit Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (57, 'street', '58 Zucchini Blossom Ct');
insert into gobfuscator_anon_data (idx, kind, value) values (58, 'street', '59 Aubergine St');
insert into gobfuscator_anon_data (idx, kind, value) values (59, 'street', '60 Broccoli Way');
insert into gobfuscator_anon_data (idx, kind, value) values (60, 'street', '61 Carrot Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (61, 'street', '62 Daikon Rd');
insert into gobfuscator_anon_data (idx, kind, value) values (62, 'street', '63 Eggplant Blvd');
insert into gobfuscator_anon_data (idx, kind, value) values (63, 'street', '64 Fennel St');
insert into gobfuscator_anon_data (idx, kind, value) values (64, 'street', '65 Gourd Way');
insert into gobfuscator_anon_data (idx, kind, value) values (65, 'street', '66 Horseradish Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (66, 'street', '67 Iceberg Lettuce Rd');
insert into gobfuscator_anon_data (idx, kind, value) values (67, 'street', '68 Jalapeno Blvd');
insert into gobfuscator_anon_data (idx, kind, value) values (68, 'street', '69 Kale Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (69, 'street', '70 Leek Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (70, 'street', '71 Mushroom Blvd');
insert into gobfuscator_anon_data (idx, kind, value) values (71, 'street', '72 Nopales Cactus Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (72, 'street', '73 Onion St');
insert into gobfuscator_anon_data (idx, kind, value) values (73, 'street', '74 Pea St');
insert into gobfuscator_anon_data (idx, kind, value) values (74, 'street', '75 Quinoa Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (75, 'street', '76 Radish Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (76, 'street', '77 Spinach Ave');
insert into gobfuscator_anon_data (idx, kind, value) values (77, 'street', '78 Tomato Blvd');
insert into gobfuscator_anon_data (idx, kind, value) values (78, 'street', '79 Ulluco Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (79, 'street', '80 Vlita Greens Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (80, 'street', '81 Watercress Blvd');
insert into gobfuscator_anon_data (idx, kind, value) values (81, 'street', '82 Xigua Melon St');
insert into gobfuscator_anon_data (idx, kind, value) values (82, 'street', '83 Youngberry Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (83, 'street', '84 Zucchini Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (84, 'street', '85 Artichoke St');
insert into gobfuscator_anon_data (idx, kind, value) values (85, 'street', '86 Bell Pepper Rd');
insert into gobfuscator_anon_data (idx, kind, value) values (86, 'street', '87 Cabbage St');
insert into gobfuscator_anon_data (idx, kind, value) values (87, 'street', '88 Daikon Radish Tr');
insert into gobfuscator_anon_data (idx, kind, value) values (88, 'street', '89 Eggplant Rd');
insert into gobfuscator_anon_data (idx, kind, value) values (89, 'street', '90 Fennel Blvd');
insert into gobfuscator_anon_data (idx, kind, value) values (90, 'street', '91 Garlic Ct');
insert into gobfuscator_anon_data (idx, kind, value) values (91, 'street', '92 Horseradish Rd');
insert into gobfuscator_anon_data (idx, kind, value) values (92, 'street', '93 Ice Plant Way');
insert into gobfuscator_anon_data (idx, kind, value) values (93, 'street', '94 Jicama Dr');
insert into gobfuscator_anon_data (idx, kind, value) values (94, 'street', '95 Kale Ln');
insert into gobfuscator_anon_data (idx, kind, value) values (95, 'street', '96 Leek Way');
insert into gobfuscator_anon_data (idx, kind, value) values (96, 'street', '97 Mushroom Blvd');
insert into gobfuscator_anon_data (idx, kind, value) values (97, 'street', '98 Nopales Rd');
insert into gobfuscator_anon_data (idx, kind, value) values (98, 'street', '99 Onion St');
insert into gobfuscator_anon_data (idx, kind, value) values (99, 'street', '100 Pea Ave');
insert into gobfuscator_anon_data (idx, kind, value) values (100, 'street', '');
insert into gobfuscator_anon_data (idx, kind, value) values (0, 'full-address', '456 Sample Avenue, Anytown, NY 54321');
insert into gobfuscator_anon_data (idx, kind, value) values (0, 'uuid', '3d50549e-24fb-442d-9a22-56ae5d4fff80');
insert into gobfuscator_anon_data (idx, kind, value) values (1, 'uuid', 'f961124f-d339-4bd1-8217-c832322ff2c8');
insert into gobfuscator_anon_data (idx, kind, value) values (2, 'uuid', '23841b36-fa62-44f9-a131-13d899a96731');
insert into gobfuscator_anon_data (idx, kind, value) values (3, 'uuid', 'ed662208-df3e-4737-aae5-3e7e5556cd9f');
insert into gobfuscator_anon_data (idx, kind, value) values (4, 'uuid', '96ce10a5-1c2b-482f-b892-e010b80933d7');
insert into gobfuscator_anon_data (idx, kind, value) values (5, 'uuid', '02bf8535-fa30-444e-878e-6ff22bcde257');
insert into gobfuscator_anon_data (idx, kind, value) values (6, 'uuid', '8e5b88b1-10eb-4c93-bc0c-d8f54a5de747');
insert into gobfuscator_anon_data (idx, kind, value) values (7, 'uuid', 'ca0e2a96-ce0e-42b4-ab2f-d216709a46d7');
insert into gobfuscator_anon_data (idx, kind, value) values (8, 'uuid', '72fd1ee1-21e9-4e3d-987a-58adc85efe37');
insert into gobfuscator_anon_data (idx, kind, value) values (9, 'uuid', 'e49c4717-2618-4e3d-b21b-842796dd6ab0');
insert into gobfuscator_anon_data (idx, kind, value) values (0, 'small-number', '5678');
insert into gobfuscator_anon_data (idx, kind, value) values (1, 'small-number', '3219');
insert into gobfuscator_anon_data (idx, kind, value) values (2, 'small-number', '7890');
insert into gobfuscator_anon_data (idx, kind, value) values (3, 'small-number', '4567');
insert into gobfuscator_anon_data (idx, kind, value) values (4, 'small-number', '9876');
insert into gobfuscator_anon_data (idx, kind, value) values (5, 'small-number', '2345');
insert into gobfuscator_anon_data (idx, kind, value) values (6, 'small-number', '6543');
insert into gobfuscator_anon_data (idx, kind, value) values (7, 'small-number', '');
insert into gobfuscator_anon_data (idx, kind, value) values (0, 'address-2', 'Apt 101');
insert into gobfuscator_anon_data (idx, kind, value) values (1, 'address-2', '');
insert into gobfuscator_anon_data (idx, kind, value) values (2, 'address-2', '');
insert into gobfuscator_anon_data (idx, kind, value) values (3, 'address-2', 'Unit 202');
insert into gobfuscator_anon_data (idx, kind, value) values (4, 'address-2', '');
insert into gobfuscator_anon_data (idx, kind, value) values (5, 'address-2', '');
insert into gobfuscator_anon_data (idx, kind, value) values (6, 'address-2', '');
insert into gobfuscator_anon_data (idx, kind, value) values (7, 'address-2', '');
insert into gobfuscator_anon_data (idx, kind, value) values (8, 'address-2', 'Suite 303');
insert into gobfuscator_anon_data (idx, kind, value) values (9, 'address-2', '');
insert into gobfuscator_anon_data (idx, kind, value) values (0, 'business', 'Northern Lights Innovations');
insert into gobfuscator_anon_data (idx, kind, value) values (1, 'business', 'Coastal Creations');
insert into gobfuscator_anon_data (idx, kind, value) values (2, 'business', 'Summit & Sage');
insert into gobfuscator_anon_data (idx, kind, value) values (3, 'business', 'The Curious Fox');
insert into gobfuscator_anon_data (idx, kind, value) values (4, 'business', 'Wanderlust Weavers');
insert into gobfuscator_anon_data (idx, kind, value) values (5, 'business', 'Copper & Clay');
insert into gobfuscator_anon_data (idx, kind, value) values (6, 'business', 'Whisper & Willow');
insert into gobfuscator_anon_data (idx, kind, value) values (7, 'business', 'Playful Penguin Products');
insert into gobfuscator_anon_data (idx, kind, value) values (8, 'business', 'Conscious Cuisine');
insert into gobfuscator_anon_data (idx, kind, value) values (9, 'business', 'The Rustic Spoon');
insert into gobfuscator_anon_data (idx, kind, value) values (10, 'business', 'Quantum Qubits');
insert into gobfuscator_anon_data (idx, kind, value) values (11, 'business', 'The Nimbus Network');
insert into gobfuscator_anon_data (idx, kind, value) values (12, 'business', 'Fusion Frameworks');
insert into gobfuscator_anon_data (idx, kind, value) values (13, 'business', 'Nexus Networks');
insert into gobfuscator_anon_data (idx, kind, value) values (14, 'business', 'Velocity Ventures');
insert into gobfuscator_anon_data (idx, kind, value) values (15, 'business', 'Prism Precision');
insert into gobfuscator_anon_data (idx, kind, value) values (16, 'business', 'Logic Luminaries');
insert into gobfuscator_anon_data (idx, kind, value) values (17, 'business', 'Pattern Pioneers');
insert into gobfuscator_anon_data (idx, kind, value) values (18, 'business', 'Spark Solutions');
insert into gobfuscator_anon_data (idx, kind, value) values (19, 'business', 'Data Drift');
insert into gobfuscator_anon_data (idx, kind, value) values (20, 'business', 'The Golden Thread');
insert into gobfuscator_anon_data (idx, kind, value) values (21, 'business', 'Harbor & Home');
insert into gobfuscator_anon_data (idx, kind, value) values (22, 'business', 'Radiant & Renewed');
insert into gobfuscator_anon_data (idx, kind, value) values (23, 'business', 'The Blooming Branch');
insert into gobfuscator_anon_data (idx, kind, value) values (24, 'business', 'The Aromatic Alcove');
insert into gobfuscator_anon_data (idx, kind, value) values (25, 'business', 'Metro Meadows');
insert into gobfuscator_anon_data (idx, kind, value) values (26, 'business', 'Wardrobe Whispers');
insert into gobfuscator_anon_data (idx, kind, value) values (27, 'business', 'Pristine Pets');
insert into gobfuscator_anon_data (idx, kind, value) values (28, 'business', 'The Thoughtful Table');
insert into gobfuscator_anon_data (idx, kind, value) values (29, 'business', 'Tranquil Territories');
insert into gobfuscator_anon_data (idx, kind, value) values (30, 'business', 'The Savory Spatula');
insert into gobfuscator_anon_data (idx, kind, value) values (31, 'business', 'Malt & Mixer');
insert into gobfuscator_anon_data (idx, kind, value) values (32, 'business', 'Flavor Frontier');
insert into gobfuscator_anon_data (idx, kind, value) values (33, 'business', 'The Roaming Bistro');
insert into gobfuscator_anon_data (idx, kind, value) values (34, 'business', 'Harvest & Honey');
insert into gobfuscator_anon_data (idx, kind, value) values (35, 'business', 'Culinary Creations');
insert into gobfuscator_anon_data (idx, kind, value) values (36, 'business', 'The Preserved Plum');
insert into gobfuscator_anon_data (idx, kind, value) values (37, 'business', 'Grounds to Growth');
insert into gobfuscator_anon_data (idx, kind, value) values (38, 'business', 'Flavors & Fusions');
insert into gobfuscator_anon_data (idx, kind, value) values (39, 'business', 'The Crafty Cask');
insert into gobfuscator_anon_data (idx, kind, value) values (40, 'business', 'Redwood Consulting');
insert into gobfuscator_anon_data (idx, kind, value) values (41, 'business', 'Aspen & Associates');
insert into gobfuscator_anon_data (idx, kind, value) values (42, 'business', 'Apex Strategies');
insert into gobfuscator_anon_data (idx, kind, value) values (43, 'business', 'Meridian Accounting');
insert into gobfuscator_anon_data (idx, kind, value) values (44, 'business', 'Summit Financial');
insert into gobfuscator_anon_data (idx, kind, value) values (45, 'business', 'Parkway Motors');
insert into gobfuscator_anon_data (idx, kind, value) values (46, 'business', 'The Keystone Legal Group');
insert into gobfuscator_anon_data (idx, kind, value) values (47, 'business', 'Horizon Realty');
insert into gobfuscator_anon_data (idx, kind, value) values (48, 'business', 'Clear View Marketing');
insert into gobfuscator_anon_data (idx, kind, value) values (49, 'business', 'Elevate Wellness');
insert into gobfuscator_anon_data (idx, kind, value) values (50, 'business', '');
insert into gobfuscator_anon_data (idx, kind, value) values (0, 'zip-codes', '35005');
insert into gobfuscator_anon_data (idx, kind, value) values (1, 'zip-codes', '99501');
insert into gobfuscator_anon_data (idx, kind, value) values (2, 'zip-codes', '85001');
insert into gobfuscator_anon_data (idx, kind, value) values (3, 'zip-codes', '71601');
insert into gobfuscator_anon_data (idx, kind, value) values (4, 'zip-codes', '90001');
insert into gobfuscator_anon_data (idx, kind, value) values (5, 'zip-codes', '80012');
insert into gobfuscator_anon_data (idx, kind, value) values (6, 'zip-codes', '06001');
insert into gobfuscator_anon_data (idx, kind, value) values (7, 'zip-codes', '19701');
insert into gobfuscator_anon_data (idx, kind, value) values (8, 'zip-codes', '32004');
insert into gobfuscator_anon_data (idx, kind, value) values (9, 'zip-codes', '30002');
insert into gobfuscator_anon_data (idx, kind, value) values (10, 'zip-codes', '96701');
insert into gobfuscator_anon_data (idx, kind, value) values (11, 'zip-codes', '83201');
insert into gobfuscator_anon_data (idx, kind, value) values (12, 'zip-codes', '60007');
insert into gobfuscator_anon_data (idx, kind, value) values (13, 'zip-codes', '46001');
insert into gobfuscator_anon_data (idx, kind, value) values (14, 'zip-codes', '50001');
insert into gobfuscator_anon_data (idx, kind, value) values (15, 'zip-codes', '66002');
insert into gobfuscator_anon_data (idx, kind, value) values (16, 'zip-codes', '40003');
insert into gobfuscator_anon_data (idx, kind, value) values (17, 'zip-codes', '70001');
insert into gobfuscator_anon_data (idx, kind, value) values (18, 'zip-codes', '04001');
insert into gobfuscator_anon_data (idx, kind, value) values (19, 'zip-codes', '20601');
insert into gobfuscator_anon_data (idx, kind, value) values (20, 'zip-codes', '01001');
insert into gobfuscator_anon_data (idx, kind, value) values (21, 'zip-codes', '48001');
insert into gobfuscator_anon_data (idx, kind, value) values (22, 'zip-codes', '55001');
insert into gobfuscator_anon_data (idx, kind, value) values (23, 'zip-codes', '38601');
insert into gobfuscator_anon_data (idx, kind, value) values (24, 'zip-codes', '63005');
insert into gobfuscator_anon_data (idx, kind, value) values (25, 'zip-codes', '59001');
insert into gobfuscator_anon_data (idx, kind, value) values (26, 'zip-codes', '68001');
insert into gobfuscator_anon_data (idx, kind, value) values (27, 'zip-codes', '88901');
insert into gobfuscator_anon_data (idx, kind, value) values (28, 'zip-codes', '03031');
insert into gobfuscator_anon_data (idx, kind, value) values (29, 'zip-codes', '07001');
insert into gobfuscator_anon_data (idx, kind, value) values (30, 'zip-codes', '87001');
insert into gobfuscator_anon_data (idx, kind, value) values (31, 'zip-codes', '10001');
insert into gobfuscator_anon_data (idx, kind, value) values (32, 'zip-codes', '27006');
insert into gobfuscator_anon_data (idx, kind, value) values (33, 'zip-codes', '58001');
insert into gobfuscator_anon_data (idx, kind, value) values (34, 'zip-codes', '43001');
insert into gobfuscator_anon_data (idx, kind, value) values (35, 'zip-codes', '73001');
insert into gobfuscator_anon_data (idx, kind, value) values (36, 'zip-codes', '97001');
insert into gobfuscator_anon_data (idx, kind, value) values (37, 'zip-codes', '15001');
insert into gobfuscator_anon_data (idx, kind, value) values (38, 'zip-codes', '02801');
insert into gobfuscator_anon_data (idx, kind, value) values (39, 'zip-codes', '29001');
insert into gobfuscator_anon_data (idx, kind, value) values (40, 'zip-codes', '57001');
insert into gobfuscator_anon_data (idx, kind, value) values (41, 'zip-codes', '37010');
insert into gobfuscator_anon_data (idx, kind, value) values (42, 'zip-codes', '75001');
insert into gobfuscator_anon_data (idx, kind, value) values (43, 'zip-codes', '84001');
insert into gobfuscator_anon_data (idx, kind, value) values (44, 'zip-codes', '05001');
insert into gobfuscator_anon_data (idx, kind, value) values (45, 'zip-codes', '20101');
insert into gobfuscator_anon_data (idx, kind, value) values (46, 'zip-codes', '98001');
insert into gobfuscator_anon_data (idx, kind, value) values (47, 'zip-codes', '24701');
insert into gobfuscator_anon_data (idx, kind, value) values (48, 'zip-codes', '53001');
insert into gobfuscator_anon_data (idx, kind, value) values (49, 'zip-codes', '82001');
insert into gobfuscator_anon_data (idx, kind, value) values (0, 'image', 'https://placeholder.com/image.png');
insert into gobfuscator_anon_data (idx, kind, value) values (1, 'image', '');
insert into gobfuscator_anon_data (idx, kind, value) values (0, 'birth-date', '1990-01-15');
insert into gobfuscator_anon_data (idx, kind, value) values (1, 'birth-date', '1991-02-22');
insert into gobfuscator_anon_data (idx, kind, value) values (2, 'birth-date', '1992-03-30');
insert into gobfuscator_anon_data (idx, kind, value) values (3, 'birth-date', '1993-04-12');
insert into gobfuscator_anon_data (idx, kind, value) values (4, 'birth-date', '1994-05-25');
insert into gobfuscator_anon_data (idx, kind, value) values (5, 'birth-date', '1995-06-18');
insert into gobfuscator_anon_data (idx, kind, value) values (6, 'birth-date', '1996-07-07');
insert into gobfuscator_anon_data (idx, kind, value) values (7, 'birth-date', '1997-08-29');
insert into gobfuscator_anon_data (idx, kind, value) values (8, 'birth-date', '1998-09-14');
insert into gobfuscator_anon_data (idx, kind, value) values (9, 'birth-date', '1999-10-31');
insert into gobfuscator_anon_data (idx, kind, value) values (10, 'birth-date', '2000-11-05');
insert into gobfuscator_anon_data (idx, kind, value) values (11, 'birth-date', '2001-12-24');


update "address" set address_1 = (select value from gobfuscator_anon_data where kind = 'address-1' and idx = mod("address".id, (select total from gobfuscater.gobfuscater_data_census where kind = 'address-1')) limit 1) || ' ' || "address".id::text,
                     address_2 = (select value from gobfuscator_anon_data where kind = 'address-2' and idx = mod("address".id, (select total from gobfuscater.gobfuscater_data_census where kind = 'address-2')) limit 1) || ' ' || "address".id::text,
                     city = (select value from gobfuscator_anon_data where kind = 'city' and idx = mod("address".id, (select total from gobfuscater.gobfuscater_data_census where kind = 'city')) limit 1) || ' ' || "address".id::text,
                     location = (select value from gobfuscator_anon_data where kind = 'geo-location' and idx = mod("address".id, (select total from gobfuscater.gobfuscater_data_census where kind = 'geo-location')) limit 1)::jsonb || ' ' || "address".id::text,
                     message = (select value from gobfuscator_anon_data where kind = 'word' and idx = mod("address".id, (select total from gobfuscater.gobfuscater_data_census where kind = 'word')) limit 1) || ' ' || "address".id::text,
                     state = (select value from gobfuscator_anon_data where kind = 'state' and idx = mod("address".id, (select total from gobfuscater.gobfuscater_data_census where kind = 'state')) limit 1) || ' ' || "address".id::text,
                     zip = (select value from gobfuscator_anon_data where kind = 'zip-codes' and idx = mod("address".id, (select total from gobfuscater.gobfuscater_data_census where kind = 'zip-codes')) limit 1) || ' ' || "address".id::text;
update "billing" set invoice_details = (select value from gobfuscator_anon_data where kind = 'word' and idx = mod("billing".id, (select total from gobfuscater.gobfuscater_data_census where kind = 'word')) limit 1) || ' ' || "billing".id::text;
update "business_attachment" set url = (select value from gobfuscator_anon_data where kind = 'word' and idx = mod("business_attachment".id, (select total from gobfuscater.gobfuscater_data_census where kind = 'word')) limit 1) || ' ' || "business_attachment".id::text;
update "contact" set email = "contact".id::text || '@example.com',
                     external_client_id = (select value from gobfuscator_anon_data where kind = 'guid' and idx = mod("contact".id, (select total from gobfuscater.gobfuscater_data_census where kind = 'guid')) limit 1) || ' ' || "contact".id::text,
                     phone = lpad("contact".id::text || "contact".id::text, 15, '0'),
                     referral_note = NULL;
update "contact_detail" set note = (select value from gobfuscator_anon_data where kind = 'word' and idx = mod("contact_detail".id, (select total from gobfuscater.gobfuscater_data_census where kind = 'word')) limit 1) || ' ' || "contact_detail".id::text;
update "download" set link = (select value from gobfuscator_anon_data where kind = 'url' and idx = mod("download".id, (select total from gobfuscater.gobfuscater_data_census where kind = 'url')) limit 1) || ' ' || "download".id::text;
update "file" set name = (select value from gobfuscator_anon_data where kind = 'business' and idx = mod("file".id, (select total from gobfuscater.gobfuscater_data_census where kind = 'business')) limit 1) || ' ' || "file".id::text,
                  notes = (select value from gobfuscator_anon_data where kind = 'chats' and idx = mod("file".id, (select total from gobfuscater.gobfuscater_data_census where kind = 'chats')) limit 1) || ' ' || "file".id::text,
                  url = (select value from gobfuscator_anon_data where kind = 'url' and idx = mod("file".id, (select total from gobfuscater.gobfuscater_data_census where kind = 'url')) limit 1) || ' ' || "file".id::text;
update "location" set address = (select value from gobfuscator_anon_data where kind = 'jsonb-address' and idx = mod("location".id, (select total from gobfuscater.gobfuscater_data_census where kind = 'jsonb-address')) limit 1)::jsonb || ' ' || "location".id::text;
update "notification" set body = (select value from gobfuscator_anon_data where kind = 'word' and idx = mod("notification".id, (select total from gobfuscater.gobfuscater_data_census where kind = 'word')) limit 1) || ' ' || "notification".id::text,
                          title = (select value from gobfuscator_anon_data where kind = 'word' and idx = mod("notification".id, (select total from gobfuscater.gobfuscater_data_census where kind = 'word')) limit 1) || ' ' || "notification".id::text;
update "payout" set file = (select value from gobfuscator_anon_data where kind = 'url' and idx = mod("payout".id, (select total from gobfuscater.gobfuscater_data_census where kind = 'url')) limit 1) || ' ' || "payout".id::text;
update "prospect" set city = (select value from gobfuscator_anon_data where kind = 'city' and idx = mod("prospect".id, (select total from gobfuscater.gobfuscater_data_census where kind = 'city')) limit 1) || ' ' || "prospect".id::text,
                      memo = (select value from gobfuscator_anon_data where kind = 'word' and idx = mod("prospect".id, (select total from gobfuscater.gobfuscater_data_census where kind = 'word')) limit 1) || ' ' || "prospect".id::text,
                      source = (select value from gobfuscator_anon_data where kind = 'word' and idx = mod("prospect".id, (select total from gobfuscater.gobfuscater_data_census where kind = 'word')) limit 1) || ' ' || "prospect".id::text;
update "request" set comments = (select value from gobfuscator_anon_data where kind = 'chats' and idx = mod("request".id, (select total from gobfuscater.gobfuscater_data_census where kind = 'chats')) limit 1) || ' ' || "request".id::text;
update "token" set entry = (select value from gobfuscator_anon_data where kind = 'word' and idx = mod("token".id, (select total from gobfuscater.gobfuscater_data_census where kind = 'word')) limit 1) || ' ' || "token".id::text;
update "user" set date_of_birth = (select value from gobfuscator_anon_data where kind = 'birth-date' and idx = mod("user".id, (select total from gobfuscater.gobfuscater_data_census where kind = 'birth-date')) limit 1)::date || ' ' || "user".id::text,
                  email = "user".id::text || '@example.com',
                  first_name = (select value from gobfuscator_anon_data where kind = 'first-name' and idx = mod("user".id, (select total from gobfuscater.gobfuscater_data_census where kind = 'first-name')) limit 1) || ' ' || "user".id::text,
                  last_name = (select value from gobfuscator_anon_data where kind = 'last-name' and idx = mod("user".id, (select total from gobfuscater.gobfuscater_data_census where kind = 'last-name')) limit 1) || ' ' || "user".id::text,
                  password = (select value from gobfuscator_anon_data where kind = 'word' and idx = mod("user".id, (select total from gobfuscater.gobfuscater_data_census where kind = 'word')) limit 1) || ' ' || "user".id::text,
                  phone = lpad("user".id::text || "user".id::text, 15, '0');


-- Drop temp tables
DROP TABLE gobfuscator_anon_data;
DROP TABLE temp_gobfuscator_data_census;

COMMIT;